repos:

  - repo: local
    hooks:
      - id: clippy
        name: clippy
        description: Lint rust sources
        entry: cargo clippy
        language: system
        args: ["--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
      - id: formatting
        name: formatting
        description: Rust standard format codestyle
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-test
        name: Run cargo test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true
